Update

diff --git a/chroot-installer b/chroot-installer
--- a/chroot-installer
+++ b/chroot-installer
@@ -10,7 +10,9 @@ WHITE="\e[0m"
 
 CHROOT_DIR=/data/local/mnt
 CONFIG_DIR=~/.chroot_installer
+LAST_ARGUMENT=$(echo "$@" | awk '{ print $NF }')
 SETUP_DIR=$CONFIG_DIR/setup
+INTERNAL_STORAGE=/sdcard
 SCRIPTS_DIR=$SETUP_DIR/scripts
 INITIAL_CONFIGS_DIR=$SETUP_DIR/configs
 BOX_CONFIGS_DIR=$SETUP_DIR/boxconfigs
@@ -25,6 +27,7 @@ do
 	argslist[$index]=$var
 	index=$((index+1))
 done
+ISRUNNING=false
 
 #Create a config file with the same name as the container
 CONFIG_FILE=$CONTAINERS_DIR/${argslist[2]}.conf
@@ -56,6 +59,291 @@ then
 	echo -e "This specific platform is not supported by any of the distros provided by this installer but you can still use a custom rootfs"
 	exit
 fi
+
+
+#check if external storage is present
+if [ -n "$(su -c ls -A /mnt/media_rw)" ]
+then
+	EXTERNAL_STORAGE=/mnt/media_rw/$(sudo ls /mnt/media_rw)
+fi
+
+#Function to allow editing config files
+edit-config(){
+
+if [ ! -f $CONTAINERS_DIR/$LAST_ARGUMENT.conf ]
+then
+	echo "No valid container has been provided, leaving now"
+	exit
+fi
+
+if [ "${argslist[2]}" == "--mark-default" ]
+then
+	mark-default
+elif [ "${argslist[2]}" == "--set-username" ]
+then
+	sed -i "3s/=.*/=${argslist[3]}/g" $CONTAINERS_DIR/$LAST_ARGUMENT.conf
+elif [ "${argslist[2]}" == "--set-path" ]
+then
+	sed -i "1s|=.*|=${argslist[3]}|g" $CONTAINERS_DIR/$LAST_ARGUMENT.conf
+fi
+	
+}
+
+#TODO Implement a way to demonize and stop it from the chroot
+xserver(){
+
+echo "Creating the socket"
+
+su -c mkdir -p $CHROOT_DIR/tmp/runtime-$USRNAME
+su -c mkdir -p $CHROOT_DIR/tmp/.X11-unix
+su -c chmod 1777 $CHROOT_DIR/tmp/.X11-unix
+mkdir -p $TMPDIR/.X11-unix
+su -c busybox chroot $CHROOT_DIR "/bin/su - root -c 'chown $USRNAME:$USRNAME /tmp/runtime-$USRNAME'"
+taskset -c 4-7 termux-x11 --no-xwayland-start & 
+sleep 7
+su -c busybox mount --bind $CHROOT_DIR/tmp/.X11-unix $TMPDIR/.X11-unix
+
+}
+
+#TODO Implement a way to demonize and eventually log to file
+virgl_server(){
+
+echo "Creating the virgl socket"
+MESA_NOERROR=1 virgl_test_server_android --use-egl-surfaceless & >/dev/null 2>&1
+sleep 4
+su -c busybox touch $CHROOT_DIR/tmp/.virgl_test
+su -c busybox mount --bind $TMPDIR/.virgl_test $CHROOT_DIR/tmp/.virgl_test
+su -c chmod a+rwx $CHROOT_DIR/tmp/.virgl_test
+	
+}
+
+
+#function that list installed containers
+list-containers(){
+
+for i in $CONTAINERS_DIR/*
+do
+	CONTAINER=$(basename -- $i)
+	echo "${CONTAINER%.*}"
+done
+	
+}
+
+
+#function that start the chroot
+start(){
+
+
+#check if Android Version is 12 and set max phantom processes
+if [ "$ANDROIDVERSION" == "12" ]
+then
+	if ! su -c device_config get activity_manager max_phantom_processes | grep -q "2147483647"
+	then
+		su -c device_config put activity_manager max_phantom_processes 2147483647
+	fi
+fi		
+
+
+
+containerslist=$(list-containers)
+
+#check if a container is already running and so start it
+if [ -f "$CONFIG_DIR/running.txt" ]
+then
+    runningcontainer=$(cat $CONFIG_DIR/running.txt)
+    if [ -f $runningcontainer ] || [ -d $runningcontainer ]
+    then
+        ISRUNNING=true
+    else
+        CONFIG=$CONTAINERS_DIR/$runningcontainer.conf
+        USERNAME=$(cat $CONFIG | awk -F '='  '/USERNAME/{print $2}')
+        INSPATH=$(cat $CONFIG | awk -F '=' '/INSPATH/{print $2}')
+        ISRUNNING=true
+    fi
+
+elif [ -f $LAST_ARGUMENT  ] || [ -d $LAST_ARGUMENT ] #check if last argument was a file or a directory
+then
+	INSPATH=$LAST_ARGUMENT
+	USERNAME=""
+	CONFIG=""
+
+#check if last argument was start or restart or -w option to know if you didn't provide any container argument
+elif ! check_parameters "$containerslist" "${argslist[*]}"
+then
+
+	if (( $(ls -1 $CONTAINERS_DIR | wc -l ) == 1 )) #check the number of available containers and if there is only one start it
+	then
+		CONFIG="$CONTAINERS_DIR/*"
+		USERNAME=$(cat $CONFIG | awk -F '='  '/USERNAME/{print $2}')
+		INSPATH=$(cat $CONFIG | awk -F '=' '/INSPATH/{print $2}')
+		
+	else  #if there are more than one container start the default
+
+		DEFAULTFOUND=false
+		for i in $CONTAINERS_DIR/*
+		do
+			if [ "$(tail -n 1 $i)" == "default" ]
+			then
+				DEFAULTFOUND=true
+				CONFIG="$i"
+				USERNAME=$(cat $CONFIG | awk -F '='  '/USERNAME/{print $2}')
+				INSPATH=$(cat $CONFIG | awk -F '=' '/INSPATH/{print $2}')
+			fi
+		done
+		if [ "$DEFAULTFOUND" == "false" ]
+		then
+			echo -e "No default container found, mark one as default or start with a container"
+			exit
+		fi
+	fi		
+#try to start the container provided by container argument		
+else
+	CONFIG="$CONTAINERS_DIR/$LAST_ARGUMENT.conf"
+	USERNAME=$(cat $CONFIG | awk -F '='  '/USERNAME/{print $2}')
+	INSPATH=$(cat $CONFIG | awk -F '=' '/INSPATH/{print $2}')
+fi
+
+if [ "$USRNAME" == "" ]
+then
+      USERNAME=root
+fi
+
+
+#check if user has prompted for a custom username
+if check_parameters "-u" "${argslist[*]}"
+then
+	USERNAME=${argslist[$((position+1))]}
+fi
+
+ if [ "$ISRUNNING" == "false" ]
+ then      
+ 	#check that the container provided is valid and in case exit
+ 	if [ "$INSPATH" == "" ]
+ 	then
+ 	    echo -e "This container seems to be damaged, exiting for safety"
+ 	    exit
+ 	fi
+
+	if [ -f $INSPATH ]
+	then
+	    INSMETHOD="file"
+	elif [ -d $INSPATH ]
+	then
+	    INSMETHOD="folder"
+	else
+	    echo -e "The container installation path doesn't seem to exist so I can't start it.Exiting"
+	    exit
+	fi
+
+	#Start audio in the chroot
+	echo -e "\nInitializing the audio server"
+		pulseaudio --start --exit-idle-time=-1
+		pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
+		
+	echo -e "\nStarting the chroot"
+#Mount the container based on installation method		
+		if findmnt $CHROOT_DIR >/dev/null
+		then
+		    su -c umount -d -l $CHROOT_DIR
+		fi
+		if [ "$INSMETHOD" == "file" ]
+		then
+			su -c busybox mount -o loop $INSPATH $CHROOT_DIR
+		else
+			su -c busybox mount --bind $INSPATH $CHROOT_DIR
+			su -c busybox mount -o remount,bind,suid,exec $CHROOT_DIR
+		fi
+		for i in dev proc sys dev/pts dev/tty
+		do
+		    su -c busybox mount --bind /$i $CHROOT_DIR/$i
+		done
+
+#Mount internal storage in chroot location /media/internal_storage
+	echo -e "\nBinding internal storage"
+        su -c mkdir -p $CHROOT_DIR/media/internal_storage
+		su -c /data/data/com.termux/files/usr/bin/bindfs -o perms=a+rwx --multithreaded $INTERNAL_STORAGE $CHROOT_DIR/media/internal_storage
+
+#Check if available then mount external storage in /media/external_storage
+		if [ -n "$(sudo ls -A /mnt/media_rw)" ]
+		then
+			echo -e "\nBinding external storage"
+			su -c mkdir -p $CHROOT_DIR/media/external_storage
+			su -c /data/data/com.termux/files/usr/bin/bindfs -o perms=a+rwx --multithreaded $EXTERNAL_STORAGE $CHROOT_DIR/media/external_storage
+		else
+			echo -e "\nSD card is not present, won't mount external storage"
+		fi
+	
+#check if binfmt_misc support is available in kernel and binfmt-support package is installed
+	if [ -d /proc/sys/fs/binfmt_misc ] && [ -f $CHROOT_DIR/usr/sbin/update-binfmts ]
+	then
+		su -c busybox mount --bind /proc/sys/fs/binfmt_misc $CHROOT_DIR/proc/sys/fs/binfmt_misc
+		echo -e "\nLoading binfmts entries"
+		su -c busybox chroot $CHROOT_DIR "/bin/su - root -c '/usr/sbin/update-binfmts --enable'"
+	else 
+		echo -e "\nBinfmt support not detected or missing binfmt-support package, skipping loading of binfmt entries"
+	fi
+	
+	
+	if check_parameters "-x" "${argslist[*]}"
+	then
+			xserver #calls the xserver function if the -x option is provided
+	fi
+
+	if check_parameters "-v" "${argslist[*]}"
+	then
+	        virgl_server #calls the xserver function if the -x option
+	fi
+	
+	echo -e "\nAll preparations completed, connecting now\n"
+	#check if login binary is available else default to an alternative method to access the chroot
+	if su -c ls $CHROOT_DIR/bin | grep -q login
+	then
+		#We check if config exists, if it doesn't it means a custom rootfs has been used
+		if [ "$CONFIG" == "" ]
+		then
+			runningcontainer=$INSPATH
+			echo "$runningcontainer" > $CONFIG_DIR/running.txt
+			su -c busybox chroot $CHROOT_DIR /bin/login -f $USRNAME
+		else
+			runningcontainer=$(get_container $CONFIG)
+			echo "$runningcontainer" > $CONFIG_DIR/running.txt
+			su -c busybox chroot $CHROOT_DIR /bin/login -f $USRNAME
+		fi
+	else
+	    su -c busybox chroot $CHROOT_DIR /bin/sh
+	fi
+else
+	echo -e "Chroot already mounted, logging in"
+	if su -c ls $CHROOT_DIR/bin | grep -q login
+	then
+		su -c busybox chroot $CHROOT_DIR /bin/login -f $USRNAME
+	else
+		su -c busybox chroot $CHROOT_DIR /bin/sh
+	fi
+fi
+
+}
+
+
+#function to stop the chroot
+stop(){
+
+rm -rf $CONFIG_DIR/running.txt
+if findmnt $CHROOT_DIR >/dev/null
+then
+	#kill termux-x11 and virgl processes if they exist
+	if [ "$PID1" != "" ];then su -c kill $(pidof app_process);fi
+	if [ "$PID2" != "" ];then su -c kill $(pidof virgl_test_server_android);fi
+	su -c umount -d -l $CHROOT_DIR
+else
+	echo -e "\nNo container seems to be mounted, exiting"
+fi
+
+
+}
+
+
+
 
 #function that makes the filesystem image where the rootfs get unpacked
 
@@ -375,7 +663,7 @@ if [ -f $CONFIG_FILE ]
 then
     USERNAME=$(cat $CONFIG_FILE | awk -F '='  '/USERNAME/{print $2}')
     INSPATH=$(cat $CONFIG_FILE | awk -F '=' '/INSPATH/{print $2}')
-    if [ "$USERNAME" == "" ] || [ "$INSPATH" == "" ]
+    if [ "$USRNAME" == "" ] || [ "$INSPATH" == "" ]
     then
         echo -e "This container seems to exist but it looks empty, so I will recreate it"
     else
@@ -683,6 +971,32 @@ do
 	then
 		remove
 		break
+    elif [ "${argslist[1]}" == "stop" ]
+	then
+		stop
+		break
+	elif [ "${argslist[1]}" == "start" ]
+    then
+    	start 
+		break
+	elif [ "${argslist[1]}" == "restart" ]
+	then
+		stop
+		start
+		break
+	elif [ "${argslist[1]}" == "list-containers" ]
+	then
+		list-containers
+		break
+	elif [ "${argslist[1]}" == "help" ]
+	then
+		help
+		break
+	elif [ "${argslist[1]}" == "edit-conf" ]
+	then
+		edit-config
+		break
+    else  
 	elif [ "${argslist[1]}" == "update" ]
 	then
 		update
@@ -690,10 +1004,6 @@ do
 	elif [ "${argslist[1]}" == "list" ]
 	then
 		list
-		break
-	elif [ "${argslist[1]}" == "help" ]
-	then
-		help
 		break
 	elif [ "${argslist[1]}" == "--version" ]
 	then
